### PR TITLE
Mixed projects

### PR DESCRIPTION
**Pull request by jzazo**
This would have the changes on master  to integrate both projects. I have included the sources of liblinear-weights, and both source projects are built when the package is added. The `build.jl` shows these changes.
I will make a second PR for the #weights branch, which should stay separate.

### CODE REVIEW

**Comment by jzazo** [comment]
Hi again innerlee. Sorry for forgetting about this for such long time. I still wanted to publish this branch if you agree with the format.

This branch should go to master, and the weights branch to an independent one. The weights branch has a slightly modified test case and they work fine locally.

**Comment by innerlee** [comment]
Thanks, does this work with the latest registration system? https://discourse.julialang.org/t/switching-package-registration-systems-soon/22677

**Comment by jzazo** [comment]
I think it does. I pulled your upstream beforehand, so it has Project.toml untouched.

**Comment by innerlee** [comment]
Okay, I'll try the new registration system later

**Pull request closed without merging**
