### PR TITLE
Use pre-built binaries via BinaryBuilder

### PR DESCRIPTION
**Pull request by aviks**
This makes the installation of this package much more robust, on multiple platforms. 

cc: @innerlee

### CODE REVIEW

**Comment by innerlee** [comment]
Thank you! I will try it later. One thing to notice is that the original source code was slightly modified to take care of the verbosity. Need to check if the verbose option is working

**Comment by aviks** [comment]
> original source code was slightly modified to take care of the verbosity

I've removed the custom print function in `libzz` , and replaced it with a `@cfunction` call in Julia. So that part is OK. But if there were changes to the liblinear C code, then if you can point me to the changes, I'll try and incorporate that. 

For the record, the build script is here: https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/liblinear/build_tarballs.jl

**Comment by innerlee** [comment]
I'll diff it later today. The change was designed for julia if I remember correctly.

**Comment by cossio** [comment]
Bump

**Comment by innerlee** [comment]
@cossio checking the changes now. It was a busy working Friday

**Comment by innerlee** [comment]
Great, thanks!

**Comment by cossio** [comment]
Thanks!

**Pull request merged**
