### PR TITLE
Fix example for julia v1.

### PR DESCRIPTION
**Pull request by jzazo**

### CODE REVIEW

**Comment by innerlee** [comment]
Hi jzazo, thanks for your contribution! I will look at the content later. A quick question, what does the `_weights` suffix mean? Is that an official functionality or just a useful modification? If the latter, how about we let master just update the package, and use a branch to add useful functionalities? With the new Julia package system, it is quite easy to use a branch now.

**Comment by jzazo** [comment]
Hi innerlee! My PR was just fixing the example to actually run on julia v1, because it needed some package loading, nothing more. I just wanted to PR the first commit, but I think every commit I make keeps being added... I don't want to do that. Let me know how if you know how to make it stop.   :S

The "weights" functionality is something the original authors of LIBLINEAR implemented, which didn't add to the main project, but set aside: https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/#weights_for_data_instances
I was trying to make this version work based on your original version. But I am not sure that this functionality should be intended for the main project. I would be happy to PR everything though, but it wouldn't be the "official" LIBLINEAR package.

**Comment by jzazo** [comment]
I will fix this PR with a new branch, sorry I tried to PR from master.

**Comment by innerlee** [comment]
no worries, thanks!

**Pull request closed without merging**
