### PR TITLE
Fixes #22

### LINKED ISSUE #22: Weights is not working
The weights key on linear_train is not working.

```julia
using RDatasets, LIBLINEAR

# Load Fisher's classic iris data
iris = dataset("datasets", "iris")

# LIBSVM handles multi-class data automatically using a one-against-one strategy
labels = convert(Vector, iris[:Species])

# First dimension of input data is features; second is instances
inst = convert(Matrix, iris[:, 1:4])'

wei = unique(labels[1:2:end])
model = linear_train(labels[1:2:end], inst[:, 1:2:end]; weights=Dict(wei[1]=> 0.5, wei[2]=> 1., wei[3] => 3.), verbose=true)
```
output:
```
ERROR: MethodError: no method matching grp2idx(::Type{Int32}, ::Base.KeySet{CategoricalString{UInt8},Dict{CategoricalString{UInt8},Float64}}, ::Dict{CategoricalString{UInt8},Int32}, ::Array{CategoricalString{UInt8},1})
Closest candidates are:
  grp2idx(::Type{S<:Real}, ::AbstractArray{T,1} where T, ::Dict{T,Int32}, ::Array{T,1}) where {T, S<:Real} at /home/tas/.julia/packages/LIBLINEAR/xcSKN/src/LIBLINEAR.jl:115
Stacktrace:
 [1] indices_and_weights(::Array{CategoricalString{UInt8},1}, ::Array{Float64,2}, ::Dict{CategoricalString{UInt8},Float64}) at /home/tas/.julia/packages/LIBLINEAR/xcSKN/src/LIBLINEAR.jl:149
 [2] #linear_train#1(::Dict{CategoricalString{UInt8},Float64}, ::Int32, ::Float64, ::Float64, ::Float64, ::Ptr{Float64}, ::Float64, ::Bool, ::typeof(linear_train), ::Array{CategoricalString{UInt8},1}, ::Array{Float64,2}) at /home/tas/.julia/packages/LIBLINEAR/xcSKN/src/LIBLINEAR.jl:235
 [3] (::getfield(LIBLINEAR, Symbol("#kw##linear_train")))(::NamedTuple{(:weights, :verbose),Tuple{Dict{CategoricalString{UInt8},Float64},Bool}}, ::typeof(linear_train), ::Array{CategoricalString{UInt8},1}, ::Array{Float64,2}) at ./none:0
 [4] top-level scope at none:0

```

### PR DESCRIPTION
**Pull request by Thuener**

### CODE REVIEW

**Comment by innerlee** [comment]
Thanks! Could you add a test?

**Comment by Thuener** [comment]
Done

**Comment by innerlee** [comment]
Thanks for re-organizing testing code! Could you fix CI's?

**Comment by Thuener** [comment]
No problem, but I have an issue with those tests, it seems that testes are unstable. I have to set the seed of the liblinear, did you know how to do that?

**Comment by innerlee** [comment]
What OS are you using, and 32bit or 64bit? Previously tests on both mac and win32 are not so stable.

**Comment by Thuener** [comment]
Ubuntu 16.04 64bits

**Comment by Thuener** [comment]
I change to use L2R_LR but x86 is still not working

**Pull request merged**
